[package]
name = "rust-remote-pi-monitor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Powerful date and time functionality
chrono = { version = "0.4.19", features = ["serde"] }
chrono-tz = "0.6"

# For connecting with the MySQL database
diesel = { version = "1.4.8", features = ["chrono"] }

# Lazy static initialization
lazy_static = "1.4.0"

# Rocket Webserver
rocket = "0.4.10"
rocket_contrib = { version = "0.4.10", features = ["json", "diesel_mysql_pool"] }

# Serialization/Deserialization
serde_json = "1.0.72"
serde = "1.0.131"
serde_derive = "1.0.131"

lettre = "0.10.0-rc.4"
